// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Aapki provide ki gayi keys ka upyog kiya gaya hai
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI5UR31WmPpc_GVY2M6dju4JkehZI4y4o',
    appId: '1:353380325588:web:15205d5382c647c0358341',
    messagingSenderId: '353380325588',
    projectId: 'employe-2dbf9',
    authDomain: 'employe-2dbf9.firebaseapp.com',
    storageBucket: 'employe-2dbf9.appspot.com',
    databaseURL: 'https://employe-2dbf9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI5UR31WmPpc_GVY2M6dju4JkehZI4y4o',
    appId: '1:353380325588:android:15205d5382c647c0358341',
    messagingSenderId: '353380325588',
    projectId: 'employe-2dbf9',
    authDomain: 'employe-2dbf9.firebaseapp.com',
    storageBucket: 'employe-2dbf9.appspot.com',
    databaseURL: 'https://employe-2dbf9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI5UR31WmPpc_GVY2M6dju4JkehZI4y4o',
    appId: '1:353380325588:ios:15205d5382c647c0358341',
    messagingSenderId: '353380325588',
    projectId: 'employe-2dbf9',
    authDomain: 'employe-2dbf9.firebaseapp.com',
    storageBucket: 'employe-2dbf9.appspot.com',
    databaseURL: 'https://employe-2dbf9-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.mobile_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI5UR31WmPpc_GVY2M6dju4JkehZI4y4o',
    appId: '1:353380325588:macos:15205d5382c647c0358341',
    messagingSenderId: '353380325588',
    projectId: 'employe-2dbf9',
    authDomain: 'employe-2dbf9.firebaseapp.com',
    storageBucket: 'employe-2dbf9.appspot.com',
    databaseURL: 'https://employe-2dbf9-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.mobile_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI5UR31WmPpc_GVY2M6dju4JkehZI4y4o',
    // DHYAN DEIN: Yeh App ID abhi web wali hai.
    // Windows ke liye Firebase Console mein ek alag Windows app add karke uski App ID yahan daalein.
    appId: '1:353380325588:web:15205d5382c647c0358341',
    messagingSenderId: '353380325588',
    projectId: 'employe-2dbf9',
    authDomain: 'employe-2dbf9.firebaseapp.com',
    storageBucket: 'employe-2dbf9.appspot.com',
    databaseURL: 'https://employe-2dbf9-default-rtdb.firebaseio.com',
  );
}