name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0' # ✅ Updated for better compatibility

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # ✅ For State Management
  provider: ^6.1.2

  # ✅ For calling REST APIs
  http: ^1.2.1

  # ✅ For saving login token
  shared_preferences: ^2.2.3

  # (Optional) For viewing JSON data, if needed
  flutter_json_view: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # ✅ Updated to a recent version

flutter:
  uses-material-design: true

  # Agar aapko future mein images use karni ho to yahan add kar sakte hain
  # assets:
  #   - assets/images/