name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.1.5

  # HTTP Requests
  http: ^1.2.1

  # Local Storage & Database
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.2
  path: ^1.9.0

  # SQLite FFI for Web/Desktop compatibility
  sqflite_common_ffi_web: ^0.4.2
  sqflite_common_ffi: ^2.3.3+1

  # Network Connectivity Check
  connectivity_plus: ^5.0.2

  # Firebase Packages
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true