name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Final Packages
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  connectivity_plus: ^5.0.2

  # Firebase Packages (Latest compatible stable versions)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true